#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Nov 09 14:07:30 EST 2024
# SW Build 5164865 on Thu Sep  5 14:36:28 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim add_sub_tb_behav -key {Behavioral:sim_1:Functional:add_sub_tb} -tclbatch add_sub_tb.tcl -log simulate.log"
xsim add_sub_tb_behav -key {Behavioral:sim_1:Functional:add_sub_tb} -tclbatch add_sub_tb.tcl -log simulate.log

